import { Inter } from "next/font/google";
import styles from "@/app/layout.module.scss";
import Sidebar from "./ui/sidebar";
import localFont from "next/font/local";

// const inter = Inter({ subsets: ["latin"] });

const myFont = localFont({ src: "./Shabnam.woff2" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <div className={styles.main}>
          {children}
          <div className={styles.sideBar}>
            <Sidebar />
          </div>
        </div>
      </body>
    </html>
  );
}
